Implement GraphQL to query and mutate entries
humanoidsbv/team-awesome-herman pull request #41
Opened 2022-03-16 15:10 UTC by HermanVulkers

2022-03-16 16:03 UTC, RubenWerdmuller requested changes, later dismissed
Looking good!

2022-03-16 16:03 UTC, RubenWerdmuller commented on pages/team-members.tsx
> +import client from "../apollo-client";
Used named export

2022-03-16 16:03 UTC, RubenWerdmuller commented on src/components/modal/DialogNewTeamMember.tsx
> +    });
const {emailAddress, firstName, lastName, role, employer, startingDate} = newTeamMember
    addNewTeamMember({
      variables: {emailAddress, firstName, lastName, role, employer, startingDate},
    });

2022-03-16 16:03 UTC, RubenWerdmuller commented on src/services/mutations.tsx
> +import { gql } from "@apollo/client";
Put the time entry query's with the time entries and the other way around 🛩️

2022-03-16 21:01 UTC, HermanVulkers commented on src/components/modal/DialogNewTeamMember.tsx
> +    });
Great refactor! Thanks :)

2022-03-17 07:23 UTC, HermanVulkers commented on pages/team-members.tsx
> +import client from "../apollo-client";
I tried this and it looks like Apollo doesn't allow named exports..

2022-03-17 09:39 UTC, fabianovangool approved these changes, later dismissed
All good!!

2022-03-17 10:19 UTC, saravdberg requested changes
Looking good! Just a few comments 👌

2022-03-17 10:19 UTC, saravdberg commented on apollo-client.ts
> +      errorPolicy: "all",
Do you need these? Do you know what they are for?

2022-03-17 10:19 UTC, saravdberg commented on pages/_app.tsx
> +import client from "../apollo-client";
I would make this a named export.

2022-03-17 10:19 UTC, saravdberg commented on pages/index.tsx
> +import client from "../apollo-client";
Named export here again.

2022-03-17 10:19 UTC, saravdberg commented on pages/index.tsx
> +  clients: ClientProps[];
Sort your props alphabetically.

2022-03-17 10:19 UTC, saravdberg commented on pages/index.tsx
> +const Homepage = ({ initialTimeEntries, clients }: HomePageProps) => {
Sort props alphabetically.

2022-03-17 10:19 UTC, saravdberg commented on pages/index.tsx
> +        <TimeEntries initialTimeEntries={initialTimeEntries} clients={clients} />
Sort props alphabetically.

2022-03-17 10:19 UTC, saravdberg commented on src/components/team-members/TeamMembers.tsx
> +          return <TeamMember teamMember={teamMember} key={teamMember.id} />;
Sort props alphabetically.

2022-03-17 10:19 UTC, saravdberg commented on src/components/time-entries/TimeEntries.tsx
> +              <TimeEntry timeEntry={timeEntry} key={timeEntry.id} />
Abccc

2022-03-17 10:39 UTC, HermanVulkers commented on pages/_app.tsx
> +import client from "../apollo-client";
Changed these to named exports, thanks :)

2022-03-17 10:43 UTC, HermanVulkers commented on apollo-client.ts
> +      errorPolicy: "all",
Yesterday we had problems rendering our components using GraphQL. Using these settings solved the issue. They prevent the use of cache when mutating the database. I only understand how it works on a superficial level, will look into it more!

2022-03-17 11:14 UTC, saravdberg approved these changes

2022-03-17 12:27 UTC, fabianovangool approved these changes
Nice clean ups!

2022-03-17 12:47 UTC, merged